---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "exercise"}}
  namespace: {{ .Values.namespace | default "rick-and-morty" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.namespace | default "rick-and-morty" }}
  template:
    metadata:
      labels:
        app: {{ .Values.namespace | default "rick-and-morty" }}
    spec:
      containers:
        - image: {{ .Values.image.registry }}/{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          name: {{ .Values.container_name | default "api" }}
      terminationGracePeriodSeconds: 10

