---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default "exercise"}}-service
  namespace: {{ .Values.namespace | default "rick-and-morty" }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.namespace | default "rick-and-morty" }} 
  ports:
    - protocol: TCP
      port: {{ .Values.port | default 80 }}
      targetPort: {{ .Values.app_port | default 8080 }}
      name: http
