---
# Source: rick-and-morty-exercise/templates/Namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: rick-and-morty
---
# Source: rick-and-morty-exercise/templates/Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: not-an-exercise-service
  namespace: rick-and-morty
spec:
  type: ClusterIP
  selector:
    app: rick-and-morty 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
---
# Source: rick-and-morty-exercise/templates/Deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-an-exercise
  namespace: rick-and-morty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rick-and-morty
  template:
    metadata:
      labels:
        app: rick-and-morty
    spec:
      containers:
        - image: quay.io/arieltw1/exercise:1.10072021-d2b5e26
          name: not-an-api
      terminationGracePeriodSeconds: 10
---
# Source: rick-and-morty-exercise/templates/Ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: not-an-exercise-ingress
  namespace: rick-and-morty
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: rick-and-morty.not-an-exercise.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: not-an-exercise-service
              servicePort: http
