name: "not-an-exercise"
namespace: "not-rick-and-not-morty"
image:
  registry: "quay.io"
  repo: "arieltw1"
  name: "exercise"
  tag: "1.10072021-40a1720"
container_name: "not-an-api"
# port: 80
# app_port: 8080
