---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise
  namespace: rick-and-morty
spec:
  replicas: 1
  selector:
    matchLabels:
      rick-and-morty: "is-cool"
  template:
    metadata:
      labels:
        rick-and-morty: "is-cool"
    spec:
      containers:
      - image: exercise:latest
        name: api
      terminationGracePeriodSeconds: 10

