name: CI
on:
  push:
    branches:
      - main
jobs:
  job1:
    name: Microk8s Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: '1.19/stable'
          addons: '["dns", "ingress"]'
      - name: Test MicroK8s
        run: |
          kubectl get no
          kubectl get pods -A -o wide
      - name: Generate CSV
        run: python3 code/gen_csv.py
      - name: Deploy 
        run: |
          docker build . -t quay.io/arieltw1/exercise:latest
          docker login -u="arieltw1+builder" -p="R975BJYCCIVS68HXVSKN3GUCVN0N58CL4WZAISPT7ZGT0A5SIKRHL9MGU2XBZ9K3" quay.io
          docker push quay.io/arieltw1/exercise:latest
          kubectl create namespace rick-and-morty
          kubectl apply -f yamls/
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: check ingress
        run: |
          kubectl get ingress -n rick-and-morty
      - name: check ingress controller
        run: |
          kubectl get pods -n rick-and-morty
          kubectl get pods -A | grep nginx-ingress-microk8s-controller | awk '{print "kubectl logs -n " $1 " " $2}' | sh
      - name: Test service URLs
        run: |
          curl -k http://localhost/   
