name: CI
on:
  push:
    branches:
      - main
jobs:
  job1:
    name: k3d-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: AbsaOSS/k3d-action@v1.5.0
        name: "Create Single Cluster"
        with:
          cluster-name: "test-cluster-1"
          args: --agents 1
      - name: Interact with the cluster
        run: kubectl get nodes
      - name: Build image
        run: |
          export SHELL=/bin/bash
          python3 code/gen_csv.py
          docker build . -t exercise:latest
      - name: Deploy to minikube
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.47.0/deploy/static/provider/cloud/deploy.yaml
          kubectl create namespace rick-and-morty
          kubectl apply -f yamls/
          kubectl get ingress -n rick-and-morty
      - name: Test service URLs
        run: |
          curl -k http://$(ip a)/   
