name: CI
on:
  push:
    branches:
      - main
jobs:
  job1:
    name: k3d-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: '1.19/stable'
          addons: '["dns", "rbac", "storage", "registry", "metrics-server"]'
      - name: Test MicroK8s
        run: |
          kubectl get no
          kubectl get pods -A -o wide
          sudo microk8s enable ingress
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      - name: check ingress controller
        run: |
          kubectl get pods -n kube-system | grep nginx-ingress-controller
      - name: Build image
        run: |
          export SHELL=/bin/bash
          python3 code/gen_csv.py
          docker build . -t exercise:latest
      - name: Deploy 
        run: |
          kubectl create namespace rick-and-morty
          kubectl apply -f yamls/
      - name: Sleep for 0 seconds
        run: sleep 30s
        shell: bash
      - name: check ingress
        run: |
          kubectl get ingress -n rick-and-morty
      - name: Test service URLs
        run: |
          curl -k http://$(ip a)/   
