name: CI
on:
  push:
    branches:
      - main
jobs:
  job1:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: kubectl get nodes
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          python3 code/gen_csv.py
          docker build . -t exercise:latest
      - name: Deploy to minikube
        run: |
          kubectl create namespace rick-and-morty
          kubectl apply -f yamls/
          kubectl get ingress -n rick-and-morty
          # kubectl expose -n rick-and-morty deployment exercise --type=NodePort --port=80
      - name: Test service URLs
        run: |
          curl -k http://$(ip -a)/   
